version: '3.3'

services:
  mysneaker-frontend:
    build: ./mysneaker/
    restart: unless-stopped
    volumes:
      - .:/mysneaker/
    expose:
      - 80
    networks:
      - proxy-network

  mysneaker-api:
    env_file: stack.env
    build: .
    command: uvicorn app.entrypoint:api --host 0.0.0.0 --reload
    restart: unless-stopped
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - proxy-network

  db:
    restart: unless-stopped
    image: postgres:14.2-alpine
    volumes:
      - postgres_data_storage:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    networks:
      - proxy-network

volumes:
  postgres_data_storage:


networks:
  proxy-network:
    name: proxy-network
    external: true
