version: '3'

services:
  frontend:
    build: ./apps/frontend/
    volumes:
      - .:/apps/frontend/
    ports:
      - 80:80

  api:
    build: ./apps/backend/
    command: uvicorn app.entrypoint:api --host 0.0.0.0 --reload
    volumes:
      - .:/apps/backend/app
    ports:
      - 8008:8000
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data_storage:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    networks:
      - default

volumes:
  postgres_data_storage:


  