import { IScenario } from 'types';

export const ScenarioSeed: IScenario[] = [
  {
    description:
      'Politik  Aufgrund der hohen Überschüsse in den Sozialkassen ist in den kommenden Perioden mit einer Absenkung der Sozialbeiträge (Personalnebenkosten) zu rechnen.  Markteinschätzung  Der wirtschaftliche Aufschwung gewinnt an Dynamik. Die Nachfrage am Markt nach Sneakern dürfte gegenüber der Vorperiode um ca. 50 % zunehmen. ',
    sneaker_price: 60,
    paint_price: 10,
    storage_fee_sneaker: 4.0,
    storage_fee_paint: 1.0,
    storage_fee_finished_sneaker: 8.0,
    employee_count_modifier_permanent: 0,
    factor_interest_rate: 0.04,
    employee_salary: 400,
    employee_signup_bonus: 100,
    employee_production_capacity: 20,
    employee_cost_modfier: 0.2,
    machine_purchase_allowed: true,
    sneaker_ask: 400,
    tender_offer_count: 0,
    factor_ad_take: 0.1,
    advertisement_allowed: true,
    employee_change_allowed: true,
    research_allowed: true,
  },
  {
    description:
      'Politik  Aufgrund der hohen Überschüsse in den Sozialkassen sinken die die Personalnebenkosten von derzeit 20% auf 18 %.  Markteinschätzung  Wichtige Indexwerte wie der IFO-Geschäftsklimaindex oder das DIW-Konjunkturbarometer steigen weiterhin deutlich, was eine gesteigerte Wirtschaftsleistung für die kommende Periode erwarten lässt. Die Nachfrage am Markt nach Sneakern dürfte gegenüber der Vorperiode weiter zunehmen.',
    sneaker_price: 65,
    paint_price: 10,
    storage_fee_sneaker: 4.0,
    storage_fee_paint: 1.0,
    storage_fee_finished_sneaker: 8.0,
    employee_count_modifier_permanent: 0,
    factor_interest_rate: 0.04,
    employee_salary: 400,
    employee_signup_bonus: 100,
    employee_production_capacity: 20,
    employee_cost_modfier: 0.18,
    machine_purchase_allowed: false,
    sneaker_ask: 600,
    tender_offer_count: 0,
    factor_ad_take: 0.1,
    advertisement_allowed: true,
    employee_change_allowed: true,
    research_allowed: true,
  },
  {
    description:
      'Politik  Aufgrund der prosperierenden Wirtschaftslage müssen Sie nach den Nullrunden der Perioden Eins und Zwei die Löhne und Gehälter um 10% anpassen.  Markteinschätzung  Die Nachfrage am Markt nach Sneakern dürfte gegenüber der Vorperiode weiter zunehmen. Eine erste Ausschreibung erfolgt in Höhe von 200 Einheiten. Verkauft wird an den günstigsten Anbieter.',
    sneaker_price: 65,
    paint_price: 12,
    storage_fee_sneaker: 4.0,
    storage_fee_paint: 1.0,
    storage_fee_finished_sneaker: 8.0,
    employee_count_modifier_permanent: 0,
    factor_interest_rate: 0.04,
    employee_salary: 440,
    employee_signup_bonus: 100,
    employee_production_capacity: 20,
    employee_cost_modfier: 0.18,
    machine_purchase_allowed: true,
    sneaker_ask: 800,
    tender_offer_count: 200,
    factor_ad_take: 0.1,
    advertisement_allowed: true,
    employee_change_allowed: true,
    research_allowed: true,
  },
  {
    description:
      'Politik  Aufgrund gesetzlicher Neuerungen bei der Dokumentation des Bewerbungsprozesses verteuert dieser sich von 100,00 € auf 200,00 €.  Markteinschätzung  Weiterhin kann ein kräftiges Wachstum auf dem Markt für Sneaker erwartet werden, dass mittelfristig anhalten wird.',
    sneaker_price: 70,
    paint_price: 12,
    storage_fee_sneaker: 4.0,
    storage_fee_paint: 1.0,
    storage_fee_finished_sneaker: 8.0,
    employee_count_modifier_permanent: 0,
    factor_interest_rate: 0.04,
    employee_salary: 440,
    employee_signup_bonus: 200,
    employee_production_capacity: 20,
    employee_cost_modfier: 0.18,
    machine_purchase_allowed: true,
    sneaker_ask: 1000,
    tender_offer_count: 200,
    factor_ad_take: 0.1,
    advertisement_allowed: true,
    employee_change_allowed: true,
    research_allowed: true,
  },
  {
    description:
      'Politik  Markteinschätzung  Die Kapazitätsgrenze für den Sneakermarkt ist nicht erreicht, dennoch erwarten die ersten Experten eine baldige Marktsättigung. Das ifo-Institut ist hingegen von einem weiterhin robusten Wachstume überzeugt. Interne Unternehmensfaktoren  Aufgrund des hohen Marktwachstums hat die Personalabteilung massive Probleme geeignete Mitarbeiter*innen zu finden, d. h. in dieser Periode kann kein neues Personal eingestellt werden.',
    sneaker_price: 80,
    paint_price: 15,
    storage_fee_sneaker: 4.0,
    storage_fee_paint: 1.0,
    storage_fee_finished_sneaker: 8.0,
    employee_count_modifier_permanent: 0,
    factor_interest_rate: 0.04,
    employee_salary: 440,
    employee_signup_bonus: 200,
    employee_production_capacity: 20,
    employee_cost_modfier: 0.18,
    machine_purchase_allowed: false,
    sneaker_ask: 1200,
    tender_offer_count: 300,
    factor_ad_take: 0.1,
    advertisement_allowed: true,
    employee_change_allowed: true,
    research_allowed: true,
  },
  {
    description:
      'Politik Markteinschätzung  Die Kapazitätsgrenze für den Sneakermarkt ist nicht erreicht, dennoch erwarten die ersten Experten eine baldige Marktsättigung. Das ifo-Institut ist hingegen von einem weiterhin robusten Wachstume überzeugt.',
    sneaker_price: 80,
    paint_price: 15,
    storage_fee_sneaker: 4.0,
    storage_fee_paint: 1.0,
    storage_fee_finished_sneaker: 8.0,
    employee_count_modifier_permanent: 0,
    factor_interest_rate: 0.04,
    employee_salary: 440,
    employee_signup_bonus: 200,
    employee_production_capacity: 10,
    employee_cost_modfier: 0.18,
    machine_purchase_allowed: true,
    sneaker_ask: 1500,
    tender_offer_count: 400,
    factor_ad_take: 0.1,
    advertisement_allowed: true,
    employee_change_allowed: true,
    research_allowed: true,
  },
];